name: Test project
on: push 
jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code from repo 
              uses: actions/checkout@v4
            - name: Install node JS
              uses: actions/setup-node@v4
            - name: Navegate to project folder and run yarn
              run: | 
                cd second-action-react-app
                yarn install
            - name: Run tests 
              run: | 
                cd second-action-react-app
                yarn test
